apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-base
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: go-base
  template:
    metadata:
      labels:
        app: go-base
    spec:
      containers:
      - name: go-base
        image: truong/go-base
        command: 
          - sh
          - '-c'
          - 'docker build -t go-base . && docker run my-custom-image'
        ports:
        - containerPort: 1234 
---
apiVersion: v1
kind: Service
metadata:
  name: go-base
spec:
  selector:
    app: go-base
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234